#!/usr/bin/env ruby
# frozen_string_literal: true

require "json"

ROOT = File.expand_path("..", __dir__)
CATALOG_PATH = File.join(ROOT, "Resources/Localizable.xcstrings")
LANGUAGES = %w[ar es hi it ja ms th ur zh-Hans].freeze

# Keep this list ordered with the catalog's missing-key query below. The script
# only fills empty values, so it is safe to run again after catalog updates.
TRANSLATIONS = [
  [
    "%@ بنيت toDō لأنني أردت تطبيق إنتاجية بسيطًا ومدروسًا وممتعًا للاستخدام كل يوم. كانت رحلة طويلة، وما زلت أعمل على تحسينه مع كل إصدار. إذا أردت معرفة المزيد عن عملي، ستجدني على iamshift.dev.",
    "%@ Construí toDō porque quería una aplicación de productividad sencilla, cuidada y agradable para usar cada día. Ha sido un largo camino y sigo mejorándola con cada versión. Si quieres saber más sobre mi trabajo, me encontrarás en iamshift.dev.",
    "%@ मैंने toDō बनाया क्योंकि मैं ऐसा उत्पादकता ऐप चाहता था जो सरल, विचारशील और हर दिन उपयोग करने में आनंददायक हो। यह एक लंबी यात्रा रही है और मैं हर रिलीज़ के साथ इसे बेहतर बना रहा हूँ। मेरे काम के बारे में जानने के लिए iamshift.dev पर आएँ।",
    "%@ Ho creato toDō perché volevo un'app per la produttività semplice, curata e piacevole da usare ogni giorno. È stato un lungo percorso e continuo a migliorarla a ogni release. Se vuoi saperne di più sul mio lavoro, mi trovi su iamshift.dev.",
    "%@ 毎日使うのが楽しく、シンプルで丁寧に作られた生産性アプリが欲しくて、toDōを作りました。長い旅でしたが、リリースのたびに改善を続けています。私の活動については iamshift.dev をご覧ください。",
    "%@ Saya membina toDō kerana saya mahukan aplikasi produktiviti yang ringkas, teliti dan menyeronokkan untuk digunakan setiap hari. Perjalanannya panjang dan saya terus memperbaikinya setiap keluaran. Ketahui lebih lanjut tentang kerja saya di iamshift.dev.",
    "%@ ฉันสร้าง toDō เพราะต้องการแอปเพิ่มประสิทธิภาพที่เรียบง่าย ใส่ใจ และใช้งานได้อย่างเพลิดเพลินทุกวัน นี่เป็นการเดินทางที่ยาวนาน และฉันยังคงปรับปรุงแอปในทุกการอัปเดต ดูงานของฉันได้ที่ iamshift.dev",
    "%@ میں نے toDō اس لیے بنایا کیونکہ میں ایک ایسی پیداواری ایپ چاہتا تھا جو سادہ، بامقصد اور ہر روز استعمال کرنے میں خوشگوار ہو۔ یہ ایک طویل سفر رہا ہے اور میں ہر ریلیز کے ساتھ اسے بہتر بنا رہا ہوں۔ میرے کام کے بارے میں iamshift.dev پر جانیں۔",
    "%@ 毅然决定制作 toDō，是因为我想要一款简单、周到且每天使用起来都愉快的效率应用。这是一段漫长的旅程，我也在持续通过每次更新让它变得更好。想了解我的工作，请访问 iamshift.dev。"
  ],
  ["%lld مكتمل", "%lld completadas", "%lld पूर्ण", "%lld completate", "%lld 件完了", "%lld selesai", "%lld รายการเสร็จสิ้น", "%lld مکمل", "已完成 %lld"],
  ["%lld مكتملة في %@", "%lld completadas el %@", "%lld पूर्ण %@ को", "%lld completate il %@", "%lld 件が %@ に完了", "%lld selesai pada %@", "%lld รายการเสร็จสิ้นเมื่อ %@", "%lld مکمل %@ کو", "%lld 已于 %@ 完成"],
  ["شكر دائم لدعمك لـ toDō منذ البداية.", "Un agradecimiento permanente por apoyar toDō desde el principio.", "शुरुआत से toDō का साथ देने के लिए आपका स्थायी धन्यवाद।", "Un ringraziamento duraturo per aver sostenuto toDō fin dall'inizio.", "初期からtoDōを応援してくださったことへの、末永い感謝です。", "Terima kasih yang tidak terhingga kerana menyokong toDō sejak awal.", "ขอบคุณอย่างยิ่งที่สนับสนุน toDō ตั้งแต่เริ่มต้น", "شروع ہی سے toDō کا ساتھ دینے کے لیے دل سے شکریہ۔", "感谢你从一开始就支持 toDō。"],
  ["قبول", "Aceptar", "स्वीकार करें", "Accetta", "承諾", "Terima", "ยอมรับ", "قبول کریں", "接受"],
  ["إضافة صورة ملف شخصي", "Añadir una imagen de perfil", "प्रोफ़ाइल चित्र जोड़ें", "Aggiungi immagine del profilo", "プロフィール画像を追加", "Tambah gambar profil", "เพิ่มรูปโปรไฟล์", "پروفائل تصویر شامل کریں", "添加头像"],
  ["ضبط صورة الملف الشخصي", "Ajustar imagen de perfil", "प्रोफ़ाइल चित्र समायोजित करें", "Regola immagine del profilo", "プロフィール画像を調整", "Laraskan gambar profil", "ปรับรูปโปรไฟล์", "پروفائل تصویر ایڈجسٹ کریں", "调整头像"],
  ["ضبط صورة الملف الشخصي", "Ajustar imagen de perfil", "प्रोफ़ाइल चित्र समायोजित करें", "Regola immagine del profilo", "プロフィール画像を調整", "Laraskan gambar profil", "ปรับรูปโปรไฟล์", "پروفائل تصویر ایڈجسٹ کریں", "调整头像"],
  ["اضبط اقتصاص صورة الملف الشخصي.", "Ajusta el recorte de la imagen de perfil.", "प्रोफ़ाइल चित्र का क्रॉप समायोजित करें।", "Regola il ritaglio dell'immagine del profilo.", "プロフィール画像の切り抜きを調整します。", "Laraskan pemotongan gambar profil.", "ปรับการครอบตัดรูปโปรไฟล์", "پروفائل تصویر کی کراپنگ ایڈجسٹ کریں۔", "调整头像裁剪位置。"],
  ["كل الأجهزة", "Todos los dispositivos", "सभी डिवाइस", "Tutti i dispositivi", "すべてのデバイス", "Semua peranti", "อุปกรณ์ทั้งหมด", "تمام آلات", "所有设备"],
  ["كل الأجهزة التي سجّلت الدخول", "Todos los dispositivos con sesión iniciada", "सभी साइन-इन किए गए डिवाइस", "Tutti i dispositivi con accesso effettuato", "サインイン済みのすべてのデバイス", "Semua peranti yang dilog masuk", "อุปกรณ์ที่ลงชื่อเข้าใช้ทั้งหมด", "تمام سائن اِن آلات", "所有已登录设备"],
  ["أجهزة Apple", "Dispositivos Apple", "Apple डिवाइस", "Dispositivi Apple", "Appleデバイス", "Peranti Apple", "อุปกรณ์ Apple", "Apple آلات", "Apple 设备"],
  ["أجهزة Apple (iCloud)", "Dispositivos Apple (iCloud)", "Apple डिवाइस (iCloud)", "Dispositivi Apple (iCloud)", "Appleデバイス（iCloud）", "Peranti Apple (iCloud)", "อุปกรณ์ Apple (iCloud)", "Apple آلات (iCloud)", "Apple 设备（iCloud）"],
  ["أجهزة Apple (غير متاحة هنا)", "Dispositivos Apple (no disponibles aquí)", "Apple डिवाइस (यहाँ उपलब्ध नहीं)", "Dispositivi Apple (non disponibili qui)", "Appleデバイス（ここでは利用できません）", "Peranti Apple (tidak tersedia di sini)", "อุปกรณ์ Apple (ไม่พร้อมใช้งานที่นี่)", "Apple آلات (یہاں دستیاب نہیں)", "Apple 设备（此处不可用）"],
  ["Apple Intelligence غير متاحة بعد على هذا الجهاز أو بهذه اللغة أو في هذه المنطقة.", "Apple Intelligence aún no está disponible en este dispositivo, idioma o región.", "Apple Intelligence अभी इस डिवाइस, भाषा या क्षेत्र में उपलब्ध नहीं है।", "Apple Intelligence non è ancora disponibile su questo dispositivo, in questa lingua o in questa regione.", "Apple Intelligenceは、このデバイス、言語、または地域ではまだ利用できません。", "Apple Intelligence belum tersedia pada peranti, bahasa atau rantau ini.", "Apple Intelligence ยังไม่พร้อมใช้งานบนอุปกรณ์ ภาษา หรือภูมิภาคนี้", "Apple Intelligence ابھی اس ڈیوائس، زبان یا خطے میں دستیاب نہیں ہے۔", "Apple Intelligence 目前尚未在此设备、语言或地区提供。"],
  ["لا يمكن إزالة toDō المشتركة", "No se puede eliminar la toDō compartida", "साझा की गई toDō हटाई नहीं जा सकती", "Impossibile rimuovere la toDō condivisa", "共有toDōを削除できません", "toDō dikongsi tidak boleh dialih keluar", "ไม่สามารถลบ toDō ที่แชร์ได้", "مشترکہ toDō ہٹائی نہیں جا سکتی", "无法移除共享 toDō"],
  ["تغيير إتاحة صورة الملف الشخصي", "Cambiar disponibilidad de la imagen de perfil", "प्रोफ़ाइल चित्र की उपलब्धता बदलें", "Modifica disponibilità immagine del profilo", "プロフィール画像の公開範囲を変更", "Tukar ketersediaan gambar profil", "เปลี่ยนการใช้งานรูปโปรไฟล์", "پروفائل تصویر کی دستیابی تبدیل کریں", "更改头像可用范围"],
  ["تغيّر مكان إتاحة صورة الملف الشخصي الحالية.", "Cambia dónde está disponible la imagen de perfil actual.", "यह बदलता है कि वर्तमान प्रोफ़ाइल चित्र कहाँ उपलब्ध है।", "Modifica dove è disponibile l'immagine del profilo attuale.", "現在のプロフィール画像を利用できる場所を変更します。", "Menukar tempat gambar profil semasa tersedia.", "เปลี่ยนตำแหน่งที่รูปโปรไฟล์ปัจจุบันพร้อมใช้งาน", "یہ طے کرتا ہے کہ موجودہ پروفائل تصویر کہاں دستیاب ہے۔", "更改当前头像的可用位置。"],
  ["تغيّر مكان إتاحة صورة ملفك الشخصي الحالية.", "Cambia dónde está disponible tu imagen de perfil actual.", "यह बदलता है कि आपका वर्तमान प्रोफ़ाइल चित्र कहाँ उपलब्ध है।", "Modifica dove è disponibile la tua immagine del profilo attuale.", "現在のプロフィール画像を利用できる場所を変更します。", "Menukar tempat gambar profil semasa anda tersedia.", "เปลี่ยนตำแหน่งที่รูปโปรไฟล์ปัจจุบันของคุณพร้อมใช้งาน", "یہ طے کرتا ہے کہ آپ کی موجودہ پروفائل تصویر کہاں دستیاب ہے۔", "更改你当前头像的可用位置。"],
  ["اختر صورة ملف شخصي قبل تغيير إتاحتها.", "Elige una imagen de perfil antes de cambiar su disponibilidad.", "उपलब्धता बदलने से पहले प्रोफ़ाइल चित्र चुनें।", "Scegli un'immagine del profilo prima di modificarne la disponibilità.", "公開範囲を変更する前にプロフィール画像を選択してください。", "Pilih gambar profil sebelum menukar ketersediaannya.", "เลือกรูปโปรไฟล์ก่อนเปลี่ยนการใช้งาน", "دستیابی تبدیل کرنے سے پہلے پروفائل تصویر منتخب کریں۔", "请先选择头像，再更改其可用范围。"],
  ["اختر صورة وحدد ما إذا كانت ستبقى على هذا الجهاز أو ستكون متاحة على أجهزتك.", "Elige una imagen y decide si se queda en este dispositivo o está disponible en tus dispositivos.", "चित्र चुनें और तय करें कि वह इसी डिवाइस पर रहे या आपके डिवाइसों पर उपलब्ध हो।", "Scegli un'immagine e stabilisci se resterà su questo dispositivo o sarà disponibile sui tuoi dispositivi.", "画像を選び、このデバイスだけに保存するか、他のデバイスでも利用できるようにするかを選択します。", "Pilih gambar dan tentukan sama ada ia kekal pada peranti ini atau tersedia pada peranti anda.", "เลือกรูปและเลือกว่าจะเก็บไว้เฉพาะอุปกรณ์นี้หรือใช้ได้บนอุปกรณ์ของคุณ", "تصویر منتخب کریں اور طے کریں کہ یہ صرف اسی آلہ پر رہے یا آپ کے آلات پر دستیاب ہو۔", "选择图片，并决定仅保留在此设备上，还是在你的设备上可用。"],
  ["اختر صورة وحدد ما إذا كانت ستبقى على هذا الـ Mac أو ستكون متاحة على أجهزتك.", "Elige una imagen y decide si se queda en este Mac o está disponible en tus dispositivos.", "चित्र चुनें और तय करें कि वह इसी Mac पर रहे या आपके डिवाइसों पर उपलब्ध हो।", "Scegli un'immagine e stabilisci se resterà su questo Mac o sarà disponibile sui tuoi dispositivi.", "画像を選び、このMacだけに保存するか、他のデバイスでも利用できるようにするかを選択します。", "Pilih gambar dan tentukan sama ada ia kekal pada Mac ini atau tersedia pada peranti anda.", "เลือกรูปและเลือกว่าจะเก็บไว้เฉพาะ Mac นี้หรือใช้ได้บนอุปกรณ์ของคุณ", "تصویر منتخب کریں اور طے کریں کہ یہ صرف اسی Mac پر رہے یا آپ کے آلات پر دستیاب ہو۔", "选择图片，并决定仅保留在此 Mac 上，还是在你的设备上可用。"],
  ["اختر صورة أصغر من 5 ميغابايت.", "Elige una imagen de menos de 5 MB.", "5 MB से छोटी छवि चुनें।", "Scegli un'immagine più piccola di 5 MB.", "5 MB未満の画像を選択してください。", "Pilih imej yang lebih kecil daripada 5 MB.", "เลือกรูปที่มีขนาดเล็กกว่า 5 MB", "5 MB سے چھوٹی تصویر منتخب کریں۔", "请选择小于 5 MB 的图片。"],
  ["اختيار صورة ملف شخصي", "Elegir imagen de perfil", "प्रोफ़ाइल चित्र चुनें", "Scegli immagine del profilo", "プロフィール画像を選択", "Pilih gambar profil", "เลือกรูปโปรไฟล์", "پروفائل تصویر منتخب کریں", "选择头像"],
  ["اختر العضوية التي تناسب طريقة عملك.", "Elige la membresía que mejor se adapte a tu forma de trabajar.", "अपने काम करने के तरीके के अनुसार सदस्यता चुनें।", "Scegli l'abbonamento più adatto al tuo modo di lavorare.", "自分の使い方に合うメンバーシップを選択してください。", "Pilih keahlian yang sesuai dengan cara anda bekerja.", "เลือกสมาชิกที่เหมาะกับวิธีการทำงานของคุณ", "اپنے کام کرنے کے انداز کے مطابق رکنیت منتخب کریں۔", "选择适合你工作方式的会员方案。"],
  ["اختر مصدر الصورة.", "Elige de dónde procede la imagen.", "चित्र का स्रोत चुनें।", "Scegli la provenienza dell'immagine.", "画像の取得元を選択", "Pilih sumber imej.", "เลือกแหล่งที่มาของรูป", "تصویر کا ماخذ منتخب کریں۔", "选择图片来源。"],
  ["اختر مكان إتاحة صورة ملفك الشخصي الحالية.", "Elige dónde está disponible tu imagen de perfil actual.", "चुनें कि आपका वर्तमान प्रोफ़ाइल चित्र कहाँ उपलब्ध है।", "Scegli dove è disponibile la tua immagine del profilo attuale.", "現在のプロフィール画像を利用できる場所を選択します。", "Pilih tempat gambar profil semasa anda tersedia.", "เลือกตำแหน่งที่รูปโปรไฟล์ปัจจุบันของคุณพร้อมใช้งาน", "اپنی موجودہ پروفائل تصویر کی دستیابی کی جگہ منتخب کریں۔", "选择当前头像的可用位置。"],
  ["اختر مكان إتاحة صورة ملفك الشخصي الحالية. يمكنك تغيير ذلك لاحقًا إذا تغيّرت أجهزتك أو إعداد المزامنة.", "Elige dónde debe estar disponible tu imagen de perfil. Puedes cambiarlo más adelante si cambian tus dispositivos o la configuración de sincronización.", "चुनें कि आपका वर्तमान प्रोफ़ाइल चित्र कहाँ उपलब्ध होना चाहिए। आपके डिवाइस या सिंक सेटअप बदलने पर इसे बाद में बदला जा सकता है।", "Scegli dove deve essere disponibile la tua immagine del profilo. Puoi cambiarlo in seguito se cambiano i tuoi dispositivi o la configurazione della sincronizzazione.", "現在のプロフィール画像を利用できる場所を選択します。デバイスや同期設定が変わった場合は、後から変更できます。", "Pilih tempat gambar profil semasa anda patut tersedia. Anda boleh menukarnya kemudian jika peranti atau tetapan penyegerakan berubah.", "เลือกตำแหน่งที่รูปโปรไฟล์ปัจจุบันควรใช้งานได้ คุณเปลี่ยนได้ภายหลังหากอุปกรณ์หรือการตั้งค่าการซิงค์เปลี่ยนไป", "منتخب کریں کہ آپ کی موجودہ پروفائل تصویر کہاں دستیاب ہو۔ آلات یا مطابقت پذیری کی ترتیبات بدلنے پر آپ اسے بعد میں تبدیل کر سکتے ہیں۔", "选择当前头像的可用范围。如果设备或同步设置发生变化，之后仍可更改。"],
  ["توضيح", "Aclaración", "स्पष्टीकरण", "Chiarimento", "確認", "Penjelasan", "คำชี้แจง", "وضاحت", "说明"],
  ["إغلاق الدعوة", "Cerrar invitación", "निमंत्रण बंद करें", "Chiudi invito", "招待を閉じる", "Tutup jemputan", "ปิดคำเชิญ", "دعوت بند کریں", "关闭邀请"],
  ["إجراءات التعاون", "Acciones de colaboración", "सहयोग कार्रवाइयाँ", "Azioni di collaborazione", "共同作業の操作", "Tindakan kolaborasi", "การดำเนินการร่วมกัน", "تعاون کے اقدامات", "协作操作"],
  ["اسم التعاون", "Nombre de la colaboración", "सहयोग का नाम", "Nome della collaborazione", "共同作業名", "Nama kolaborasi", "ชื่อการทำงานร่วมกัน", "تعاون کا نام", "协作名称"],
  ["إيقاع الإنجاز خلال الأسابيع الـ 16 الماضية.", "Ritmo de finalización durante las últimas 16 semanas.", "पिछले 16 सप्ताहों में पूर्णता की लय।", "Ritmo dei completamenti nelle ultime 16 settimane.", "過去16週間の完了リズム。", "Rentak penyelesaian sepanjang 16 minggu lalu.", "จังหวะการทำงานที่เสร็จสิ้นในช่วง 16 สัปดาห์ที่ผ่านมา", "گزشتہ 16 ہفتوں میں تکمیل کی رفتار۔", "过去 16 周的完成节奏。"],
  ["تأكيد صورة الملف الشخصي", "Confirmar imagen de perfil", "प्रोफ़ाइल चित्र की पुष्टि करें", "Conferma immagine del profilo", "プロフィール画像を確認", "Sahkan gambar profil", "ยืนยันรูปโปรไฟล์", "پروفائل تصویر کی تصدیق کریں", "确认头像"],
  ["إنشاء باستخدام Apple Intelligence", "Crear con Apple Intelligence", "Apple Intelligence के साथ बनाएँ", "Crea con Apple Intelligence", "Apple Intelligenceで作成", "Cipta dengan Apple Intelligence", "สร้างด้วย Apple Intelligence", "Apple Intelligence کے ساتھ بنائیں", "使用 Apple Intelligence 创建"],
  ["حذف التعاون", "Eliminar colaboración", "सहयोग हटाएँ", "Elimina collaborazione", "共同作業を削除", "Padam kolaborasi", "ลบการทำงานร่วมกัน", "تعاون حذف کریں", "删除协作"],
  ["حذف التعاون؟", "¿Eliminar la colaboración?", "सहयोग हटाएँ?", "Eliminare la collaborazione?", "共同作業を削除しますか？", "Padam kolaborasi?", "ลบการทำงานร่วมกันไหม", "تعاون حذف کریں؟", "删除协作？"],
  ["جارٍ حذف التعاون", "Eliminando colaboración", "सहयोग हटाया जा रहा है", "Eliminazione della collaborazione", "共同作業を削除中", "Memadam kolaborasi", "กำลังลบการทำงานร่วมกัน", "تعاون حذف کیا جا رہا ہے", "正在删除协作"],
  ["صِف toDō كاملة بشكل طبيعي. ينظّم التطبيق تفاصيلها ويطرح سؤال متابعة قصيرًا عند الحاجة.", "Describe una toDō completa de forma natural. La app organiza sus detalles y hace una breve pregunta de seguimiento cuando es necesario.", "एक पूर्ण toDō को स्वाभाविक रूप से बताएँ। ऐप उसके विवरण व्यवस्थित करता है और ज़रूरत होने पर एक छोटा पूरक प्रश्न पूछता है।", "Descrivi una toDō completa in modo naturale. L'app ne organizza i dettagli e fa una breve domanda di chiarimento solo quando serve.", "完成したtoDōを自然に説明してください。アプリが詳細を整理し、必要なときだけ短い確認質問をします。", "Huraikan toDō lengkap secara semula jadi. Aplikasi menyusun butirannya dan bertanya soalan ringkas jika perlu.", "อธิบาย toDō ให้ครบถ้วนอย่างเป็นธรรมชาติ แอปจะจัดระเบียบรายละเอียดและถามคำถามสั้น ๆ เมื่อจำเป็น", "ایک مکمل toDō کو قدرتی انداز میں بیان کریں۔ ایپ اس کی تفصیلات ترتیب دیتی ہے اور ضرورت پڑنے پر مختصر سوال پوچھتی ہے۔", "自然地描述一个完整的 toDō。应用会整理其详细信息，并仅在需要时提出简短的后续问题。"],
  ["صِف toDō، بما في ذلك أي تاريخ استحقاق أو تذكير أو تكرار أو علامات أو NanoDos أو ملاحظات أو موقع.", "Describe la toDō, incluyendo cualquier fecha límite, recordatorio, repetición, etiqueta, NanoDo, nota o ubicación.", "toDō का वर्णन करें, जिसमें नियत तारीख, रिमाइंडर, दोहराव, टैग, NanoDos, नोट्स या स्थान शामिल हो।", "Descrivi la toDō, includendo eventuali scadenze, promemoria, ripetizioni, tag, NanoDos, note o luoghi.", "期限、リマインダー、繰り返し、タグ、NanoDos、メモ、場所などを含めてtoDōを説明してください。", "Huraikan toDō, termasuk tarikh akhir, peringatan, pengulangan, tag, NanoDos, nota atau lokasi.", "อธิบาย toDō รวมถึงวันครบกำหนด การเตือน การทำซ้ำ แท็ก NanoDos โน้ต หรือตำแหน่ง", "toDō کی تفصیل بتائیں، جس میں مقررہ تاریخ، یاد دہانی، تکرار، ٹیگز، NanoDos، نوٹس یا مقام شامل ہو۔", "描述 toDō，包括截止日期、提醒、重复、标签、NanoDos、备注或位置。"],
  ["اضغط مرتين لمراجعة تفاصيل العضوية", "Toca dos veces para revisar los detalles de la membresía", "सदस्यता विवरण देखने के लिए दो बार टैप करें", "Tocca due volte per rivedere i dettagli dell'abbonamento", "メンバーシップの詳細を確認するにはダブルタップ", "Ketuk dua kali untuk menyemak butiran keahlian", "แตะสองครั้งเพื่อดูรายละเอียดสมาชิก", "رکنیت کی تفصیلات دیکھنے کے لیے دو بار ٹیپ کریں", "轻点两下以查看会员详情"],
  ["اسحب الصورة لاختيار نقطة المركز.", "Arrastra la imagen para elegir el punto central.", "केंद्र बिंदु चुनने के लिए चित्र खींचें।", "Trascina l'immagine per scegliere il punto centrale.", "画像をドラッグして中心点を選択します。", "Seret gambar untuk memilih titik tengah.", "ลากรูปเพื่อเลือกจุดกึ่งกลาง", "مرکز کا نقطہ منتخب کرنے کے لیے تصویر کو گھسیٹیں۔", "拖动图片以选择中心点。"],
  ["دعوة عبر البريد الإلكتروني", "Invitación por correo electrónico", "ईमेल आमंत्रण", "Invito via email", "メールで招待", "Jemputan e-mel", "คำเชิญทางอีเมล", "ای میل دعوت", "电子邮件邀请"],
  ["أدخل عنوان بريد إلكتروني صالحًا للشخص الذي تريد دعوته.", "Introduce una dirección de correo válida para la persona a la que quieres invitar.", "जिस व्यक्ति को आमंत्रित करना है उसका मान्य ईमेल पता दर्ज करें।", "Inserisci un indirizzo email valido per la persona che vuoi invitare.", "招待する相手の有効なメールアドレスを入力してください。", "Masukkan alamat e-mel yang sah untuk orang yang ingin anda jemput.", "ป้อนที่อยู่อีเมลที่ถูกต้องของผู้ที่คุณต้องการเชิญ", "جسے آپ مدعو کرنا چاہتے ہیں اس کا درست ای میل پتہ درج کریں۔", "输入你要邀请的人的有效电子邮件地址。"],
  ["أدخل رابط صورة آمنًا وصالحًا.", "Introduce un enlace de imagen seguro y válido.", "मान्य सुरक्षित चित्र लिंक दर्ज करें।", "Inserisci un link immagine sicuro e valido.", "有効で安全な画像リンクを入力してください。", "Masukkan pautan imej selamat yang sah.", "ป้อนลิงก์รูปที่ปลอดภัยและถูกต้อง", "درست محفوظ تصویر کا لنک درج کریں۔", "输入有效的安全图片链接。"],
  ["كل ميزة، المجانية والمدفوعة، متاحة الآن وفي المستقبل.", "Todas las funciones, gratuitas y de pago, están incluidas ahora y en el futuro.", "हर सुविधा, मुफ़्त और सशुल्क, अभी और आगे भी शामिल है।", "Tutte le funzioni, gratuite e a pagamento, sono incluse ora e in futuro.", "無料・有料を問わず、現在と今後のすべての機能が含まれます。", "Setiap ciri, percuma dan berbayar, disertakan sekarang dan pada masa hadapan.", "ทุกฟีเจอร์ทั้งฟรีและเสียเงิน รวมอยู่ในตอนนี้และอนาคต", "ہر فیچر، مفت اور ادا شدہ، ابھی اور مستقبل میں شامل ہے۔", "所有功能，无论免费还是付费，现在及未来都包含在内。"],
  ["من %@", "De %@", "%@ से", "Da %@", "%@ から", "Daripada %@", "จาก %@", "%@ سے", "来自 %@"],
  ["تعذر على تسجيل الدخول عبر Google فتح جلسة المتصفح الآمنة. حاول مرة أخرى.", "Google no pudo abrir la sesión segura del navegador. Inténtalo de nuevo.", "Google साइन-इन सुरक्षित ब्राउज़र सत्र नहीं खोल सका। फिर कोशिश करें।", "Google non ha potuto aprire la sessione sicura del browser. Riprova.", "Googleサインインで安全なブラウザセッションを開けませんでした。もう一度お試しください。", "Log masuk Google tidak dapat membuka sesi pelayar selamat. Cuba lagi.", "การลงชื่อเข้าใช้ Google ไม่สามารถเปิดเซสชันเบราว์เซอร์ที่ปลอดภัยได้ ลองอีกครั้ง", "Google سائن اِن محفوظ براؤزر سیشن نہیں کھول سکا۔ دوبارہ کوشش کریں۔", "Google 登录无法打开安全浏览器会话。请重试。"],
  ["انتهى تسجيل الدخول عبر Google من دون إعادة استدعاء. حاول مرة أخرى.", "Google terminó el inicio de sesión sin devolver una llamada. Inténtalo de nuevo.", "Google साइन-इन कॉलबैक लौटाए बिना समाप्त हुआ। फिर कोशिश करें।", "L'accesso con Google è terminato senza restituire un callback. Riprova.", "Googleサインインがコールバックを返さずに終了しました。もう一度お試しください。", "Log masuk Google selesai tanpa mengembalikan panggilan balik. Cuba lagi.", "การลงชื่อเข้าใช้ Google เสร็จสิ้นโดยไม่ส่งคืนคอลแบ็ก ลองอีกครั้ง", "Google سائن اِن نے کال بیک واپس کیے بغیر مکمل کیا۔ دوبارہ کوشش کریں۔", "Google 登录结束时未返回回调。请重试。"],
  ["مرحبًا، أنا moin.", "Hola, soy moin.", "नमस्कार, मैं moin हूँ।", "Ciao, sono moin.", "こんにちは、moinです。", "Hai, saya moin.", "สวัสดี ฉันคือ moin", "ہیلو، میں moin ہوں۔", "你好，我是 moin。"],
  ["https://…", "https://…", "https://…", "https://…", "https://…", "https://…", "https://…", "https://…", "https://…"],
  ["تعذر تطبيق إجابتك. لم يتم حفظ أي شيء.", "No pude aplicar esa respuesta. No se guardó nada.", "मैं उस उत्तर को लागू नहीं कर सका। कुछ भी सहेजा नहीं गया।", "Non ho potuto applicare quella risposta. Non è stato salvato nulla.", "回答を適用できませんでした。何も保存されませんでした。", "Jawapan itu tidak dapat digunakan. Tiada apa-apa disimpan.", "ใช้คำตอบนั้นไม่ได้ ไม่มีการบันทึกข้อมูล", "میں اس جواب کو لاگو نہیں کر سکا۔ کچھ بھی محفوظ نہیں ہوا۔", "无法应用该回答。没有保存任何内容。"],
  ["تعذر العثور على هذا الموقع. ما المكان الذي تريد استخدامه؟", "No encontré esa ubicación. ¿Qué lugar quieres usar?", "मुझे वह स्थान नहीं मिला। आप किस स्थान का उपयोग करना चाहते हैं?", "Non ho trovato quella posizione. Quale luogo vuoi usare?", "その場所が見つかりませんでした。どの場所を使いますか？", "Lokasi itu tidak ditemui. Tempat manakah yang ingin anda gunakan?", "ไม่พบตำแหน่งนั้น คุณต้องการใช้สถานที่ใด", "مجھے وہ مقام نہیں ملا۔ آپ کون سا مقام استعمال کرنا چاہتے ہیں؟", "找不到该位置。你想使用哪个地点？"],
  ["تعذر تنظيم ذلك في toDō. لم يتم حفظ أي شيء.", "No pude organizar eso en una toDō. No se guardó nada.", "मैं उसे toDō में व्यवस्थित नहीं कर सका। कुछ भी सहेजा नहीं गया।", "Non ho potuto organizzarlo in una toDō. Non è stato salvato nulla.", "それをtoDōに整理できませんでした。何も保存されませんでした。", "Perkara itu tidak dapat disusun menjadi toDō. Tiada apa-apa disimpan.", "จัดสิ่งนั้นเป็น toDō ไม่ได้ ไม่มีการบันทึกข้อมูล", "میں اسے toDō میں ترتیب نہیں دے سکا۔ کچھ بھی محفوظ نہیں ہوا۔", "无法将其整理为 toDō。没有保存任何内容。"],
  ["صور iCloud الشخصية غير متاحة على هذا الجهاز. اختر هذا الجهاز أو كل الأجهزة التي سجّلت الدخول.", "Las imágenes de perfil de iCloud no están disponibles en este dispositivo. Elige este dispositivo o todos los dispositivos con sesión iniciada.", "इस डिवाइस पर iCloud प्रोफ़ाइल चित्र उपलब्ध नहीं हैं। यह डिवाइस या सभी साइन-इन किए गए डिवाइस चुनें।", "Le immagini del profilo iCloud non sono disponibili su questo dispositivo. Scegli questo dispositivo o tutti i dispositivi con accesso.", "このデバイスではiCloudプロフィール画像を利用できません。このデバイス、またはサインイン済みのすべてのデバイスを選択してください。", "Gambar profil iCloud tidak tersedia pada peranti ini. Pilih peranti ini atau semua peranti yang dilog masuk.", "รูปโปรไฟล์ iCloud ไม่พร้อมใช้งานบนอุปกรณ์นี้ เลือกอุปกรณ์นี้หรืออุปกรณ์ที่ลงชื่อเข้าใช้ทั้งหมด", "اس ڈیوائس پر iCloud پروفائل تصاویر دستیاب نہیں۔ یہ ڈیوائس یا تمام سائن اِن آلات منتخب کریں۔", "此设备无法使用 iCloud 头像。请选择此设备或所有已登录设备。"],
  ["صور iCloud الشخصية غير متاحة على هذا الـ Mac. اختر هذا الـ Mac أو كل الأجهزة التي سجّلت الدخول.", "Las imágenes de perfil de iCloud no están disponibles en este Mac. Elige este Mac o todos los dispositivos con sesión iniciada.", "इस Mac पर iCloud प्रोफ़ाइल चित्र उपलब्ध नहीं हैं। यह Mac या सभी साइन-इन किए गए डिवाइस चुनें।", "Le immagini del profilo iCloud non sono disponibili su questo Mac. Scegli questo Mac o tutti i dispositivi con accesso.", "このMacではiCloudプロフィール画像を利用できません。このMac、またはサインイン済みのすべてのデバイスを選択してください。", "Gambar profil iCloud tidak tersedia pada Mac ini. Pilih Mac ini atau semua peranti yang dilog masuk.", "รูปโปรไฟล์ iCloud ไม่พร้อมใช้งานบน Mac นี้ เลือก Mac นี้หรืออุปกรณ์ที่ลงชื่อเข้าใช้ทั้งหมด", "اس Mac پر iCloud پروفائل تصاویر دستیاب نہیں۔ یہ Mac یا تمام سائن اِن آلات منتخب کریں۔", "此 Mac 无法使用 iCloud 头像。请选择此 Mac 或所有已登录设备。"],
  ["إتاحة الصورة", "Disponibilidad de la imagen", "चित्र उपलब्धता", "Disponibilità immagine", "画像の可用範囲", "Ketersediaan imej", "การใช้งานรูป", "تصویر کی دستیابی", "图片可用范围"],
  ["رابط الصورة", "Enlace de imagen", "चित्र लिंक", "Link immagine", "画像リンク", "Pautan imej", "ลิงก์รูป", "تصویر کا لنک", "图片链接"],
  ["تم إرسال الدعوة. اختر البريد الإلكتروني أو المشاركة لإرسالها من هذا الـ Mac.", "Invitación enviada. Elige Correo o Compartir para enviarla desde este Mac.", "आमंत्रण भेजा गया। इस Mac से भेजने के लिए ईमेल या शेयर चुनें।", "Invito inviato. Scegli Email o Condividi per inviarlo da questo Mac.", "招待を送信しました。このMacから送るにはメールまたは共有を選択してください。", "Jemputan dihantar. Pilih E-mel atau Kongsi untuk menghantarnya daripada Mac ini.", "ส่งคำเชิญแล้ว เลือกอีเมลหรือแชร์เพื่อส่งจาก Mac นี้", "دعوت بھیج دی گئی۔ اس Mac سے بھیجنے کے لیے ای میل یا شیئر منتخب کریں۔", "邀请已发送。选择“邮件”或“共享”以从此 Mac 发送。"],
  ["تم إرسال الدعوة. إذا لم يكن العنوان مسجلاً بعد، فستبقى معلقة حتى ينضم المستخدم إلى toDō.", "Invitación enviada. Si la dirección aún no está registrada, quedará pendiente hasta que se una a toDō.", "आमंत्रण भेजा गया। यदि पता अभी पंजीकृत नहीं है, तो उपयोगकर्ता के toDō में शामिल होने तक यह लंबित रहेगा।", "Invito inviato. Se l'indirizzo non è ancora registrato, resterà in sospeso finché l'utente non si unirà a toDō.", "招待を送信しました。まだ登録されていないアドレスの場合、toDōに参加するまで保留されます。", "Jemputan dihantar. Jika alamat itu belum didaftarkan, ia akan kekal belum selesai sehingga mereka menyertai toDō.", "ส่งคำเชิญแล้ว หากที่อยู่นี้ยังไม่ได้ลงทะเบียน คำเชิญจะคงค้างจนกว่าจะเข้าร่วม toDō", "دعوت بھیج دی گئی۔ اگر پتہ ابھی رجسٹرڈ نہیں تو صارف کے toDō میں شامل ہونے تک یہ زیر التوا رہے گی۔", "邀请已发送。如果该地址尚未注册，邀请会一直待处理，直到对方加入 toDō。"],
  ["الدعوة غير متاحة", "Invitación no disponible", "निमंत्रण उपलब्ध नहीं", "Invito non disponibile", "招待を利用できません", "Jemputan tidak tersedia", "คำเชิญไม่พร้อมใช้งาน", "دعوت دستیاب نہیں", "邀请不可用"],
  ["انضم إليّ في %@ على toDō. افتح التطبيق لقبول الدعوة.", "Únete a mí en %@ en toDō. Abre la app para aceptar la invitación.", "toDō में %@ पर मेरे साथ जुड़ें। निमंत्रण स्वीकार करने के लिए ऐप खोलें।", "Unisciti a me su %@ in toDō. Apri l'app per accettare l'invito.", "toDōの%@に参加してください。アプリを開いて招待を承諾します。", "Sertai saya di %@ dalam toDō. Buka aplikasi untuk menerima jemputan.", "เข้าร่วม %@ กับฉันใน toDō เปิดแอปเพื่อยอมรับคำเชิญ", "toDō پر %@ میں میرے ساتھ شامل ہوں۔ دعوت قبول کرنے کے لیے ایپ کھولیں۔", "在 toDō 的 %@ 中加入我。打开应用以接受邀请。"],
  ["انضم إليّ في %@ على toDō. افتح هذا الرابط لمراجعة الدعوة:\n%@", "Únete a mí en %@ en toDō. Abre este enlace para revisar la invitación:\n%@", "toDō में %@ पर मेरे साथ जुड़ें। निमंत्रण देखने के लिए यह लिंक खोलें:\n%@", "Unisciti a me su %@ in toDō. Apri questo link per rivedere l'invito:\n%@", "toDōの%@に参加してください。このリンクを開いて招待を確認します:\n%@", "Sertai saya di %@ dalam toDō. Buka pautan ini untuk menyemak jemputan:\n%@", "เข้าร่วม %@ กับฉันใน toDō เปิดลิงก์นี้เพื่อดูคำเชิญ:\n%@", "toDō پر %@ میں میرے ساتھ شامل ہوں۔ دعوت کا جائزہ لینے کے لیے یہ لنک کھولیں:\n%@", "在 toDō 的 %@ 中加入我。打开此链接以查看邀请：\n%@"],
  ["احتفظ بها على هذا الجهاز، أو شاركها عبر الأجهزة التي سجّلت الدخول من خلال toDō.", "Guárdala en este dispositivo o compártela entre tus dispositivos con sesión iniciada mediante toDō.", "इसे इसी डिवाइस पर रखें या toDō के ज़रिए साइन-इन किए गए डिवाइसों पर साझा करें।", "Tientila su questo dispositivo oppure condividila tra i dispositivi con accesso tramite toDō.", "このデバイスに保存するか、toDōを通じてサインイン済みのデバイス間で共有します。", "Simpannya pada peranti ini atau kongsikannya merentas peranti yang dilog masuk melalui toDō.", "เก็บไว้ในอุปกรณ์นี้หรือแชร์ไปยังอุปกรณ์ที่ลงชื่อเข้าใช้ผ่าน toDō", "اسے اسی ڈیوائس پر رکھیں یا toDō کے ذریعے سائن اِن آلات پر شیئر کریں۔", "保留在此设备上，或通过 toDō 在已登录设备之间共享。"],
  ["احتفظ بها على هذا الجهاز، أو شاركها مع أجهزة Apple عبر iCloud.", "Guárdala en este dispositivo o compártela con tus dispositivos Apple mediante iCloud.", "इसे इसी डिवाइस पर रखें या iCloud के ज़रिए अपने Apple डिवाइसों पर साझा करें।", "Tientila su questo dispositivo oppure condividila con i dispositivi Apple tramite iCloud.", "このデバイスに保存するか、iCloudを通じてAppleデバイスと共有します。", "Simpannya pada peranti ini atau kongsikannya dengan peranti Apple melalui iCloud.", "เก็บไว้ในอุปกรณ์นี้หรือแชร์ไปยังอุปกรณ์ Apple ผ่าน iCloud", "اسے اسی ڈیوائس پر رکھیں یا iCloud کے ذریعے Apple آلات پر شیئر کریں۔", "保留在此设备上，或通过 iCloud 与 Apple 设备共享。"],
  ["احتفظ بها على هذا الـ Mac، أو شاركها عبر الأجهزة التي سجّلت الدخول من خلال toDō.", "Guárdala en este Mac o compártela entre tus dispositivos con sesión iniciada mediante toDō.", "इसे इसी Mac पर रखें या toDō के ज़रिए साइन-इन किए गए डिवाइसों पर साझा करें।", "Tientila su questo Mac oppure condividila tra i dispositivi con accesso tramite toDō.", "このMacに保存するか、toDōを通じてサインイン済みのデバイス間で共有します。", "Simpannya pada Mac ini atau kongsikannya merentas peranti yang dilog masuk melalui toDō.", "เก็บไว้ใน Mac นี้หรือแชร์ไปยังอุปกรณ์ที่ลงชื่อเข้าใช้ผ่าน toDō", "اسے اسی Mac پر رکھیں یا toDō کے ذریعے سائن اِن آلات پر شیئر کریں۔", "保留在此 Mac 上，或通过 toDō 在已登录设备之间共享。"],
  ["احتفظ بها على هذا الـ Mac، أو شاركها مع أجهزة Apple عبر iCloud.", "Guárdala en este Mac o compártela con tus dispositivos Apple mediante iCloud.", "इसे इसी Mac पर रखें या iCloud के ज़रिए अपने Apple डिवाइसों पर साझा करें।", "Tientila su questo Mac oppure condividila con i dispositivi Apple tramite iCloud.", "このMacに保存するか、iCloudを通じてAppleデバイスと共有します。", "Simpannya pada Mac ini atau kongsikannya dengan peranti Apple melalui iCloud.", "เก็บไว้ใน Mac นี้หรือแชร์ไปยังอุปกรณ์ Apple ผ่าน iCloud", "اسے اسی Mac پر رکھیں یا iCloud کے ذریعے Apple آلات پر شیئر کریں۔", "保留在此 Mac 上，或通过 iCloud 与 Apple 设备共享。"],
  ["اجعل اسم المستخدم بحد أقصى %lld حرفًا.", "Usa un nombre de usuario de %lld caracteres como máximo.", "उपयोगकर्ता नाम को %lld वर्णों या कम का रखें।", "Mantieni il nome utente entro %lld caratteri.", "ユーザー名は%lld文字以内にしてください。", "Hadkan nama pengguna kepada %lld aksara atau kurang.", "ใช้ชื่อผู้ใช้ไม่เกิน %lld ตัวอักษร", "اپنے صارف نام کو %lld حروف یا اس سے کم رکھیں۔", "用户名不得超过 %lld 个字符。"],
  ["أقل", "Menos", "कम", "Meno", "少なく", "Kurang", "น้อยกว่า", "کم", "更少"],
  ["جارٍ تحميل عمليات التعاون", "Cargando colaboraciones", "सहयोग लोड हो रहे हैं", "Caricamento collaborazioni", "共同作業を読み込み中", "Memuatkan kolaborasi", "กำลังโหลดการทำงานร่วมกัน", "تعاون لوڈ ہو رہے ہیں", "正在加载协作"],
  ["جارٍ تحميل الدعوة", "Cargando invitación", "निमंत्रण लोड हो रहा है", "Caricamento invito", "招待を読み込み中", "Memuatkan jemputan", "กำลังโหลดคำเชิญ", "دعوت لوڈ ہو رہی ہے", "正在加载邀请"],
  ["المزيد", "Más", "अधिक", "Altro", "その他", "Lagi", "เพิ่มเติม", "مزید", "更多"],
  ["غير متصل", "No conectado", "कनेक्ट नहीं है", "Non connesso", "未接続", "Tidak bersambung", "ไม่ได้เชื่อมต่อ", "منسلک نہیں", "未连接"],
  ["لم يتم حفظ أي شيء.", "No se guardó nada.", "कुछ भी सहेजा नहीं गया।", "Non è stato salvato nulla.", "何も保存されませんでした。", "Tiada apa-apa disimpan.", "ไม่มีการบันทึกข้อมูล", "کچھ بھی محفوظ نہیں ہوا۔", "没有保存任何内容。"],
  ["اعتراف لمرة واحدة متاح لمدة 14 يومًا بعد الإطلاق", "Reconocimiento único disponible durante 14 días después del lanzamiento", "लॉन्च के बाद 14 दिनों तक एक बार का सम्मान उपलब्ध", "Riconoscimento una tantum disponibile per 14 giorni dal lancio", "リリース後14日間、一度限りの認定を利用できます", "Pengiktirafan sekali sahaja tersedia selama 14 hari selepas pelancaran", "การยกย่องแบบครั้งเดียวมีให้ใช้ภายใน 14 วันหลังเปิดตัว", "لانچ کے بعد 14 دن تک ایک بار کی شناخت دستیاب ہے", "发布后 14 天内可获得一次性认可"],
  ["مالك التعاون وحده يستطيع إزالته.", "Solo el propietario de la colaboración puede eliminarla.", "केवल सहयोग का मालिक इसे हटा सकता है।", "Solo il proprietario della collaborazione può rimuoverla.", "共同作業の所有者だけが削除できます。", "Hanya pemilik kolaborasi boleh mengalih keluarnya.", "เฉพาะเจ้าของการทำงานร่วมกันเท่านั้นที่ลบได้", "صرف تعاون کا مالک اسے ہٹا سکتا ہے۔", "只有协作所有者可以移除它。"],
  ["لا يستطيع إلا مالك toDō أو مالك القائمة المشتركة إزالته.", "Solo el propietario de la toDō o de la lista compartida puede eliminarla.", "केवल toDō का मालिक या साझा सूची का मालिक इसे हटा सकता है।", "Solo il proprietario della toDō o della lista condivisa può rimuoverla.", "toDōの所有者または共有リストの所有者だけが削除できます。", "Hanya pemilik toDō atau senarai dikongsi boleh mengalih keluarnya.", "เฉพาะเจ้าของ toDō หรือเจ้าของรายการที่แชร์เท่านั้นที่ลบได้", "صرف toDō کا مالک یا مشترکہ فہرست کا مالک اسے ہٹا سکتا ہے۔", "只有 toDō 所有者或共享列表所有者可以移除它。"],
  ["فتح ملفي الشخصي", "Abrir mi perfil", "मेरी प्रोफ़ाइल खोलें", "Apri il mio profilo", "マイプロフィールを開く", "Buka Profil Saya", "เปิดโปรไฟล์ของฉัน", "میرا پروفائل کھولیں", "打开我的个人资料"],
  ["شكر اختياري لمرة واحدة. لا تفتح هذه المشتريات أي ميزات.", "Agradecimiento opcional de un solo pago. Estas compras no desbloquean funciones.", "वैकल्पिक एकमुश्त धन्यवाद। इन खरीदों से सुविधाएँ अनलॉक नहीं होतीं।", "Ringraziamento opzionale una tantum. Questi acquisti non sbloccano funzioni.", "任意の一度限りの応援です。これらの購入で機能は解放されません。", "Penghargaan sekali sahaja secara pilihan. Pembelian ini tidak membuka ciri.", "การขอบคุณแบบซื้อครั้งเดียวที่เลือกได้ การซื้อเหล่านี้ไม่ปลดล็อกฟีเจอร์", "اختیاری ایک بار کا شکریہ۔ ان خریداریوں سے کوئی فیچر ان لاک نہیں ہوتا۔", "可选的一次性致谢。这些购买不会解锁功能。"],
  ["نظّم ${request} في toDō", "Organiza ${request} en toDō", "${request} को toDō में व्यवस्थित करें", "Organizza ${request} in toDō", "${request}をtoDōに整理", "Susun ${request} dalam toDō", "จัด ${request} ใน toDō", "${request} کو toDō میں منظم کریں", "在 toDō 中整理 ${request}"],
  ["المالك · انضم %lld", "Propietario · %lld se unieron", "मालिक · %lld शामिल हुए", "Proprietario · %lld partecipanti", "所有者 · %lld人が参加", "Pemilik · %lld menyertai", "เจ้าของ · เข้าร่วม %lld คน", "مالک · %lld شامل ہوئے", "所有者 · 已加入 %lld 人"],
  ["الصور", "Fotos", "फ़ोटो", "Foto", "写真", "Foto", "รูปภาพ", "تصاویر", "照片"],
  ["تم حفظ صورة الملف الشخصي.", "Imagen de perfil guardada.", "प्रोफ़ाइल चित्र सहेजा गया।", "Immagine del profilo salvata.", "プロフィール画像を保存しました。", "Gambar profil disimpan.", "บันทึกรูปโปรไฟล์แล้ว", "پروفائل تصویر محفوظ ہو گئی۔", "头像已保存。"],
  ["استرداد رمز العرض", "Canjear código de oferta", "ऑफ़र कोड रिडीम करें", "Riscatta codice offerta", "オファーコードを利用", "Tebus Kod Tawaran", "แลกรหัสข้อเสนอ", "آفر کوڈ استعمال کریں", "兑换优惠码"],
  ["طلب", "Solicitud", "अनुरोध", "Richiesta", "リクエスト", "Permintaan", "คำขอ", "درخواست", "请求"],
  ["إعادة تعيين", "Restablecer", "रीसेट", "Reimposta", "リセット", "Tetapkan semula", "รีเซ็ต", "ری سیٹ", "重置"],
  ["إعادة ضبط الموضع", "Restablecer posición", "स्थिति रीसेट करें", "Reimposta posizione", "位置をリセット", "Tetapkan semula kedudukan", "รีเซ็ตตำแหน่ง", "پوزیشن ری سیٹ کریں", "重置位置"],
  ["العودة إلى الجولة", "Volver al recorrido", "टूर पर लौटें", "Torna al tour", "ツアーに戻る", "Kembali ke lawatan", "กลับไปที่ทัวร์", "ٹور پر واپس جائیں", "返回引导"],
  ["راجع القائمة المشتركة قبل أن تقرر الانضمام إليها.", "Revisa la lista compartida antes de decidir si te unes.", "शामिल होने का निर्णय लेने से पहले साझा सूची की समीक्षा करें।", "Esamina la lista condivisa prima di decidere se partecipare.", "参加を決める前に共有リストを確認してください。", "Semak senarai dikongsi sebelum memutuskan untuk menyertainya.", "ตรวจสอบรายการที่แชร์ก่อนตัดสินใจเข้าร่วม", "شامل ہونے کا فیصلہ کرنے سے پہلے مشترکہ فہرست کا جائزہ لیں۔", "在决定加入共享列表之前，请先查看它。"],
  ["راجع toDō الجديدة هنا. استخدم زر السهم إذا أردت تعديلها. عندما تكون جاهزًا، اضغط على xmark المميز للعودة إلى الجولة.", "Revisa aquí tu nueva toDō. Usa el botón de flecha si quieres editarla. Cuando estés listo, toca la xmark resaltada para volver al recorrido.", "अपनी नई toDō यहाँ देखें। संपादित करने के लिए तीर बटन का उपयोग करें। तैयार होने पर टूर पर लौटने के लिए हाइलाइट किए गए xmark पर टैप करें।", "Rivedi qui la tua nuova toDō. Usa il pulsante freccia se vuoi modificarla. Quando sei pronto, tocca la xmark evidenziata per tornare al tour.", "ここで新しいtoDōを確認します。編集する場合は矢印ボタンを使います。準備ができたら、ハイライトされたxmarkをタップしてツアーに戻ります。", "Semak toDō baharu anda di sini. Gunakan butang anak panah jika mahu mengeditnya. Apabila bersedia, ketik xmark yang diserlahkan untuk kembali ke lawatan.", "ดู toDō ใหม่ของคุณที่นี่ ใช้ปุ่มลูกศรหากต้องการแก้ไข เมื่อพร้อม แตะ xmark ที่ไฮไลต์เพื่อกลับไปที่ทัวร์", "اپنی نئی toDō کا یہاں جائزہ لیں۔ ترمیم کے لیے تیر کا بٹن استعمال کریں۔ تیار ہونے پر ٹور پر واپس جانے کے لیے نمایاں xmark کو ٹیپ کریں۔", "在此查看你的新 toDō。若要编辑，请使用箭头按钮。准备好后，轻点高亮的 xmark 返回引导。"],
  ["احفظ هذه الصورة عبر أجهزة toDō التي سجّلت الدخول.", "Guarda esta imagen en tus dispositivos toDō con sesión iniciada.", "इस चित्र को अपने साइन-इन किए गए toDō डिवाइसों पर सहेजें।", "Salva questa immagine sui dispositivi toDō con accesso effettuato.", "この画像をサインイン済みのtoDōデバイス間で保存します。", "Simpan imej ini merentas peranti toDō yang dilog masuk.", "บันทึกรูปนี้บนอุปกรณ์ toDō ที่ลงชื่อเข้าใช้", "اس تصویر کو اپنے سائن اِن toDō آلات پر محفوظ کریں۔", "将此图片保存到已登录的 toDō 设备。"],
  ["احفظ هذه الصورة لأجهزة Apple عبر iCloud.", "Guarda esta imagen para tus dispositivos Apple mediante iCloud.", "इस चित्र को iCloud के ज़रिए अपने Apple डिवाइसों के लिए सहेजें।", "Salva questa immagine per i dispositivi Apple tramite iCloud.", "この画像をiCloud経由でAppleデバイス用に保存します。", "Simpan imej ini untuk peranti Apple melalui iCloud.", "บันทึกรูปนี้สำหรับอุปกรณ์ Apple ผ่าน iCloud", "اس تصویر کو iCloud کے ذریعے Apple آلات کے لیے محفوظ کریں۔", "通过 iCloud 将此图片保存到 Apple 设备。"],
  ["احفظ هذه الصورة على هذا الجهاز فقط.", "Guarda esta imagen solo en este dispositivo.", "इस चित्र को केवल इसी डिवाइस पर सहेजें।", "Salva questa immagine solo su questo dispositivo.", "この画像をこのデバイスだけに保存します。", "Simpan imej ini pada peranti ini sahaja.", "บันทึกรูปนี้ไว้ในอุปกรณ์นี้เท่านั้น", "اس تصویر کو صرف اسی ڈیوائس پر محفوظ کریں۔", "仅将此图片保存到此设备。"],
  ["احفظ هذه الصورة على هذا الـ Mac فقط.", "Guarda esta imagen solo en este Mac.", "इस चित्र को केवल इसी Mac पर सहेजें।", "Salva questa immagine solo su questo Mac.", "この画像をこのMacだけに保存します。", "Simpan imej ini pada Mac ini sahaja.", "บันทึกรูปนี้ไว้ใน Mac นี้เท่านั้น", "اس تصویر کو صرف اسی Mac پر محفوظ کریں۔", "仅将此图片保存到此 Mac。"],
  ["جارٍ حفظ صورة الملف الشخصي", "Guardando imagen de perfil", "प्रोफ़ाइल चित्र सहेजा जा रहा है", "Salvataggio immagine del profilo", "プロフィール画像を保存中", "Menyimpan gambar profil", "กำลังบันทึกรูปโปรไฟล์", "پروفائل تصویر محفوظ ہو رہی ہے", "正在保存头像"],
  ["مشاركة الدعوة", "Compartir invitación", "निमंत्रण साझा करें", "Condividi invito", "招待を共有", "Kongsi jemputan", "แชร์คำเชิญ", "دعوت شیئر کریں", "共享邀请"],
  ["shift تحت المشهد", "shift bajo la vista", "दृश्य के नीचे shift", "shift sotto la vista", "shift beneath the view", "shift di bawah paparan", "shift ใต้เบื้องหน้า", "shift منظر کے نیچے", "shift beneath the view"],
  ["يعرض ملاحظات الإصدار لكل إصدار", "Muestra las notas de versión de cada versión", "हर संस्करण के रिलीज़ नोट दिखाता है", "Mostra le note di rilascio di ogni versione", "すべてのバージョンのリリースノートを表示", "Menunjukkan nota keluaran bagi setiap versi", "แสดงบันทึกประจำรุ่นของทุกเวอร์ชัน", "ہر ورژن کے ریلیز نوٹس دکھاتا ہے", "显示每个版本的发行说明"],
  ["يعرض ملف حسابك الشخصي.", "Muestra tu perfil de cuenta.", "आपकी खाता प्रोफ़ाइल दिखाता है।", "Mostra il profilo del tuo account.", "アカウントプロフィールを表示します。", "Menunjukkan profil akaun anda.", "แสดงโปรไฟล์บัญชีของคุณ", "آپ کے اکاؤنٹ کا پروفائل دکھاتا ہے۔", "显示你的账户资料。"],
  ["يعرض ملفك الشخصي وتفاصيل حسابك.", "Muestra tu perfil y los detalles de tu cuenta.", "आपकी प्रोफ़ाइल और खाता विवरण दिखाता है।", "Mostra il tuo profilo e i dettagli del tuo account.", "プロフィールとアカウントの詳細を表示します。", "Menunjukkan profil dan butiran akaun anda.", "แสดงโปรไฟล์และรายละเอียดบัญชีของคุณ", "آپ کا پروفائل اور اکاؤنٹ کی تفصیلات دکھاتا ہے۔", "显示你的个人资料和账户详情。"],
  ["سجّل الدخول لتغيير إتاحة الصورة.", "Inicia sesión para cambiar la disponibilidad de la imagen.", "चित्र की उपलब्धता बदलने के लिए साइन इन करें।", "Accedi per modificare la disponibilità dell'immagine.", "画像の公開範囲を変更するにはサインインしてください。", "Log masuk untuk menukar ketersediaan gambar.", "ลงชื่อเข้าใช้เพื่อเปลี่ยนการใช้งานรูป", "تصویر کی دستیابی تبدیل کرنے کے لیے سائن اِن کریں۔", "登录以更改图片可用范围。"],
  ["تسجيل الدخول للمراجعة", "Iniciar sesión para revisar", "समीक्षा के लिए साइन इन करें", "Accedi per esaminare", "確認のためにサインイン", "Log masuk untuk menyemak", "ลงชื่อเข้าใช้เพื่อดู", "جائزے کے لیے سائن اِن کریں", "登录以查看"],
  ["سجّل الدخول إلى الحساب الذي تلقى هذه الدعوة لمراجعتها.", "Inicia sesión en la cuenta que recibió esta invitación para revisarla.", "इस निमंत्रण को देखने के लिए इसे प्राप्त करने वाले खाते में साइन इन करें।", "Accedi all'account che ha ricevuto questo invito per esaminarlo.", "この招待を受け取ったアカウントにサインインして確認してください。", "Log masuk ke akaun yang menerima jemputan ini untuk menyemaknya.", "ลงชื่อเข้าใช้บัญชีที่ได้รับคำเชิญนี้เพื่อดูรายละเอียด", "اس دعوت کا جائزہ لینے کے لیے اسے موصول کرنے والے اکاؤنٹ میں سائن اِن کریں۔", "登录收到此邀请的账户以查看。"],
  ["صفحة الإحصاءات %lld من %lld", "Página de estadísticas %lld de %lld", "आँकड़े पृष्ठ %lld में %lld", "Pagina statistiche %lld di %lld", "統計ページ %lld / %lld", "Halaman statistik %lld daripada %lld", "หน้าสถิติ %lld จาก %lld", "اعدادوشمار صفحہ %lld از %lld", "统计页面 %lld / %lld"],
  ["صفحة الإحصاءات %lld من 6", "Página de estadísticas %lld de 6", "6 में से आँकड़े पृष्ठ %lld", "Pagina statistiche %lld di 6", "統計ページ %lld / 6", "Halaman statistik %lld daripada 6", "หน้าสถิติ %lld จาก 6", "6 میں سے اعدادوشمار صفحہ %lld", "统计页面 %lld / 6"],
  ["قسم الإحصاءات %lld من 6", "Sección de estadísticas %lld de 6", "6 में से आँकड़े अनुभाग %lld", "Sezione statistiche %lld di 6", "統計セクション %lld / 6", "Bahagian statistik %lld daripada 6", "ส่วนสถิติ %lld จาก 6", "6 میں سے اعدادوشمار سیکشن %lld", "统计部分 %lld / 6"],
  ["ابقَ محليًا لهذا الجهاز، أو استخدم iCloud عبر أجهزة Apple، أو سجّل الدخول لاستخدام toDō Sync على iPhone وiPad وWatch وMac وAndroid والويب. راجع هذه الشاشة، ثم استخدم سهم الرجوع للعودة إلى الجولة أو تابع أدناه.", "Mantén los datos locales en este dispositivo, usa iCloud entre dispositivos Apple o inicia sesión para usar toDō Sync en iPhone, iPad, Watch, Mac, Android y la web. Revisa esta pantalla y usa la flecha atrás para volver al recorrido o continuar abajo.", "इस डिवाइस पर स्थानीय रूप से रहें, Apple डिवाइसों में iCloud का उपयोग करें, या iPhone, iPad, Watch, Mac, Android और वेब पर toDō Sync उपयोग करने के लिए साइन इन करें। इस स्क्रीन की समीक्षा करें, फिर टूर पर लौटने के लिए पीछे तीर का उपयोग करें या नीचे जारी रखें।", "Resta locale su questo dispositivo, usa iCloud tra i dispositivi Apple oppure accedi per usare toDō Sync su iPhone, iPad, Watch, Mac, Android e web. Esamina questa schermata, poi usa la freccia indietro per tornare al tour o continua qui sotto.", "このデバイスだけでローカルに使うか、Appleデバイス間でiCloudを使うか、サインインしてiPhone、iPad、Watch、Mac、Android、WebでtoDō Syncを使えます。この画面を確認し、戻る矢印でツアーに戻るか、下へ進みます。", "Kekalkan setempat untuk peranti ini, gunakan iCloud merentas peranti Apple, atau log masuk untuk menggunakan toDō Sync pada iPhone, iPad, Watch, Mac, Android dan web. Semak skrin ini, kemudian gunakan anak panah kembali untuk kembali ke lawatan atau teruskan di bawah.", "ใช้แบบเฉพาะอุปกรณ์นี้ ใช้ iCloud ระหว่างอุปกรณ์ Apple หรือลงชื่อเข้าใช้เพื่อใช้ toDō Sync บน iPhone, iPad, Watch, Mac, Android และเว็บ ตรวจสอบหน้าจอนี้ แล้วใช้ลูกศรย้อนกลับเพื่อกลับไปที่ทัวร์หรือดำเนินการต่อด้านล่าง", "اس ڈیوائس کے لیے مقامی رہیں، Apple آلات پر iCloud استعمال کریں، یا iPhone، iPad، Watch، Mac، Android اور ویب پر toDō Sync استعمال کرنے کے لیے سائن اِن کریں۔ اس اسکرین کا جائزہ لیں، پھر ٹور پر واپس جانے کے لیے پیچھے کا تیر استعمال کریں یا نیچے جاری رکھیں۔", "仅在此设备本地使用，或在 Apple 设备之间使用 iCloud；也可以登录后在 iPhone、iPad、Watch、Mac、Android 和 Web 上使用 toDō Sync。查看此页面，然后使用返回箭头返回引导，或继续向下。"],
  ["خذ وقتًا قصيرًا للاستكشاف. جرّب طرقًا مختلفة لتنظيم مهامك، واجعل التطبيق يناسبك، واكتشف ما يناسبك. زر yourtodo.today لمعرفة المزيد عن toDō، وتابع Substack للحصول على ملاحظات الإصدار والحديث الهندسي والتفكير وراء كل تحديث.", "Tómate un tiempo para explorar. Prueba distintas formas de organizar tus tareas, personaliza la app y descubre qué funciona para ti. Visita yourtodo.today para saber más sobre toDō y sigue mi Substack para notas de versión, ingeniería y las ideas detrás de cada actualización.", "थोड़ा समय लेकर देखें। अपने कार्यों को व्यवस्थित करने के अलग-अलग तरीके आज़माएँ, ऐप को अपने अनुसार बनाएँ और देखें कि आपके लिए क्या काम करता है। toDō के बारे में अधिक जानने के लिए yourtodo.today पर जाएँ और रिलीज़ नोट्स, इंजीनियरिंग चर्चा और हर अपडेट के पीछे की सोच के लिए मेरा Substack देखें।", "Prenditi un po' di tempo per esplorare. Prova diversi modi di organizzare le attività, personalizza l'app e scopri cosa funziona per te. Visita yourtodo.today per saperne di più su toDō e segui il mio Substack per note di rilascio, ingegneria e idee dietro ogni aggiornamento.", "少し時間をかけて試してみてください。タスクの整理方法をいろいろ試し、アプリを自分に合わせて、合う使い方を見つけましょう。toDōについては yourtodo.today、リリースノートや開発の話、更新の背景は私のSubstackをご覧ください。", "Luangkan sedikit masa untuk meneroka. Cuba pelbagai cara mengatur tugas, jadikan aplikasi ini milik anda dan lihat perkara yang berkesan. Lawati yourtodo.today untuk mengetahui lebih lanjut tentang toDō, dan ikuti Substack saya untuk nota keluaran, perbualan kejuruteraan dan pemikiran di sebalik setiap kemas kini.", "ใช้เวลาสักนิดเพื่อสำรวจ ลองจัดระเบียบงานหลายรูปแบบ ปรับแอปให้เหมาะกับคุณ และดูว่าวิธีไหนใช้ได้ผล เยี่ยมชม yourtodo.today เพื่อเรียนรู้เพิ่มเติมเกี่ยวกับ toDō และติดตาม Substack ของฉันสำหรับบันทึกประจำรุ่น เรื่องวิศวกรรม และแนวคิดเบื้องหลังการอัปเดตแต่ละครั้ง", "تھوڑی دیر دریافت کرنے میں گزاریں۔ اپنے کاموں کو ترتیب دینے کے مختلف طریقے آزمائیں، ایپ کو اپنے مطابق بنائیں اور دیکھیں کہ آپ کے لیے کیا کارآمد ہے۔ toDō کے بارے میں مزید جاننے کے لیے yourtodo.today دیکھیں اور ریلیز نوٹس، انجینئرنگ گفتگو اور ہر اپ ڈیٹ کے پیچھے سوچ کے لیے میرا Substack فالو کریں۔", "花一点时间探索。尝试不同的任务整理方式，让应用适合你自己，并找到最适合你的方法。访问 yourtodo.today 了解更多 toDō 信息，并关注我的 Substack，获取发行说明、工程分享和每次更新背后的思考。"],
  ["تعذر تحميل رابط الصورة.", "No se pudo cargar el enlace de imagen.", "चित्र लिंक लोड नहीं किया जा सका।", "Non è stato possibile caricare il link dell'immagine.", "画像リンクを読み込めませんでした。", "Pautan imej tidak dapat dimuatkan.", "โหลดลิงก์รูปไม่ได้", "تصویر کا لنک لوڈ نہیں ہو سکا۔", "无法加载图片链接。"],
  ["اسم المستخدم هذا مستخدم بالفعل. اختر اسمًا آخر.", "Ese nombre de usuario ya está en uso. Elige otro.", "यह उपयोगकर्ता नाम पहले से उपयोग में है। दूसरा चुनें।", "Questo nome utente è già in uso. Scegline un altro.", "そのユーザー名はすでに使用されています。別の名前を選んでください。", "Nama pengguna itu sudah digunakan. Pilih yang lain.", "ชื่อผู้ใช้นี้ถูกใช้แล้ว เลือกชื่ออื่น", "یہ صارف نام پہلے ہی استعمال میں ہے۔ دوسرا منتخب کریں۔", "该用户名已被使用。请选择其他用户名。"],
  ["تعذر تنزيل صورة الملف الشخصي الحالية. حاول مرة أخرى.", "No se pudo descargar la imagen de perfil actual. Inténtalo de nuevo.", "वर्तमान प्रोफ़ाइल चित्र डाउनलोड नहीं किया जा सका। फिर कोशिश करें।", "Non è stato possibile scaricare l'immagine del profilo attuale. Riprova.", "現在のプロフィール画像をダウンロードできませんでした。もう一度お試しください。", "Gambar profil semasa tidak dapat dimuat turun. Cuba lagi.", "ดาวน์โหลดรูปโปรไฟล์ปัจจุบันไม่ได้ ลองอีกครั้ง", "موجودہ پروفائل تصویر ڈاؤن لوڈ نہیں ہو سکی۔ دوبارہ کوشش کریں۔", "无法下载当前头像。请重试。"],
  ["تعذر قراءة صورة الملف الشخصي. جرّب صورة أخرى.", "No se pudo leer la imagen de perfil. Prueba con otra imagen.", "प्रोफ़ाइल चित्र पढ़ा नहीं जा सका। दूसरा चित्र आज़माएँ।", "Non è stato possibile leggere l'immagine del profilo. Prova con un'altra immagine.", "プロフィール画像を読み込めませんでした。別の画像をお試しください。", "Gambar profil tidak dapat dibaca. Cuba gambar lain.", "อ่านรูปโปรไฟล์ไม่ได้ ลองใช้รูปอื่น", "پروفائل تصویر پڑھی نہیں جا سکی۔ کوئی دوسری تصویر آزمائیں۔", "无法读取头像。请尝试其他图片。"],
  ["هذا الجهاز", "Este dispositivo", "यह डिवाइस", "Questo dispositivo", "このデバイス", "Peranti ini", "อุปกรณ์นี้", "یہ ڈیوائس", "此设备"],
  ["هنا تقرر ما إذا كان ينبغي أرشفة toDō أو نقلها إلى سلة المهملات عند إزالتها. راجع الاختيار، ثم استخدم سهم الرجوع للعودة إلى الجولة أو تابع أدناه.", "Aquí decides si una toDō debe archivarse o enviarse a la papelera al quitarla. Revisa la elección y usa la flecha atrás para volver al recorrido o continuar abajo.", "यहाँ आप तय करते हैं कि toDō हटाने पर उसे संग्रहित करना है या ट्रैश में भेजना है। विकल्प की समीक्षा करें, फिर टूर पर लौटने के लिए पीछे तीर का उपयोग करें या नीचे जारी रखें।", "Qui decidi se una toDō rimossa deve essere archiviata o spostata nel cestino. Esamina la scelta, poi usa la freccia indietro per tornare al tour o continua qui sotto.", "ここでは、toDōを削除するときにアーカイブするかゴミ箱へ移動するかを決めます。選択を確認し、戻る矢印でツアーに戻るか、下へ進みます。", "Di sini anda menentukan sama ada toDō yang dibuang perlu diarkibkan atau dihantar ke tong sampah. Semak pilihan, kemudian gunakan anak panah kembali untuk kembali ke lawatan atau teruskan di bawah.", "ที่นี่คุณเลือกว่าจะเก็บถาวรหรือย้าย toDō ไปที่ถังขยะเมื่อเอาออก ตรวจสอบตัวเลือก แล้วใช้ลูกศรย้อนกลับเพื่อกลับไปที่ทัวร์หรือดำเนินการต่อด้านล่าง", "یہاں آپ فیصلہ کرتے ہیں کہ toDō ہٹانے پر اسے آرکائیو کرنا ہے یا ٹریش میں بھیجنا ہے۔ انتخاب کا جائزہ لیں، پھر ٹور پر واپس جانے کے لیے پیچھے کا تیر استعمال کریں یا نیچے جاری رکھیں۔", "在这里决定移除 toDō 时是归档还是移到废纸篓。查看选择，然后使用返回箭头返回引导，或继续向下。"],
  ["يؤدي هذا إلى إزالة القائمة المشتركة ووصولها للجميع. لا يمكن التراجع عن ذلك.", "Esto elimina la lista compartida y su acceso para todos. No se puede deshacer.", "यह साझा सूची और सभी के लिए उसकी पहुँच हटा देता है。 इसे पूर्ववत नहीं किया जा सकता।", "Rimuove la lista condivisa e il relativo accesso per tutti. Non può essere annullato.", "共有リストと全員のアクセスを削除します。この操作は取り消せません。", "Ini mengalih keluar senarai dikongsi dan aksesnya untuk semua orang. Tindakan ini tidak boleh dibuat asal.", "การดำเนินการนี้จะลบรายการที่แชร์และการเข้าถึงของทุกคน ไม่สามารถเลิกทำได้", "یہ مشترکہ فہرست اور سب کے لیے اس کی رسائی ہٹا دیتا ہے۔ اسے واپس نہیں کیا جا سکتا۔", "这会移除共享列表及所有人的访问权限，且无法撤销。"],
  ["حساب toDō", "Cuenta de toDō", "toDō खाता", "Account toDō", "toDōアカウント", "Akaun toDō", "บัญชี toDō", "toDō اکاؤنٹ", "toDō 账户"],
  ["يطلب toDō إذن الإشعارات هنا لأن التذكيرات لا تهم إلا بعد أن تقرر استخدامها. يمكنك تغيير ذلك لاحقًا في الإعدادات. استخدم سهم الرجوع عندما تكون جاهزًا للعودة إلى الجولة.", "toDō solicita permiso para las notificaciones aquí porque los recordatorios solo importan cuando decides usarlos. Puedes cambiarlo más tarde en Ajustes. Usa la flecha atrás cuando estés listo para volver al recorrido.", "toDō यहाँ नोटिफ़िकेशन अनुमति माँगता है क्योंकि रिमाइंडर तब ही उपयोगी हैं जब आप उनका उपयोग करना चुनें। इसे बाद में सेटिंग्स में बदल सकते हैं। टूर पर लौटने के लिए तैयार होने पर पीछे तीर का उपयोग करें।", "toDō chiede qui il permesso per le notifiche perché i promemoria servono solo dopo aver deciso di usarli. Puoi modificarlo in seguito nelle impostazioni. Usa la freccia indietro quando sei pronto a tornare al tour.", "toDōがここで通知の許可を求めるのは、リマインダーを使うと決めた後に役立つ機能だからです。後から設定で変更できます。準備ができたら戻る矢印でツアーに戻ります。", "toDō meminta kebenaran pemberitahuan di sini kerana peringatan hanya berguna selepas anda memilih untuk menggunakannya. Anda boleh menukarnya kemudian dalam Tetapan. Gunakan anak panah kembali apabila bersedia untuk kembali ke lawatan.", "toDō ขออนุญาตการแจ้งเตือนที่นี่ เพราะการเตือนจะมีประโยชน์เมื่อคุณเลือกใช้เท่านั้น คุณเปลี่ยนได้ภายหลังใน Settings ใช้ลูกศรย้อนกลับเมื่อพร้อมกลับไปที่ทัวร์", "toDō یہاں نوٹیفکیشن کی اجازت مانگتی ہے کیونکہ یاد دہانیاں تب ہی اہم ہیں جب آپ انہیں استعمال کرنے کا فیصلہ کریں۔ آپ اسے بعد میں Settings میں تبدیل کر سکتے ہیں۔ ٹور پر واپس جانے کے لیے تیار ہونے پر پیچھے کا تیر استعمال کریں۔", "toDō 在这里请求通知权限，因为提醒只有在你决定使用后才有意义。之后可以在设置中更改。准备好返回引导时，请使用返回箭头。"],
  ["دعوة تعاون toDō لـ %@\n\n%@\n\nالمدعو: %@", "Invitación de colaboración de toDō para %@\n\n%@\n\nInvitado: %@", "%@ के लिए toDō सहयोग निमंत्रण\n\n%@\n\nआमंत्रित: %@", "Invito alla collaborazione toDō per %@\n\n%@\n\nInvitato: %@", "%@へのtoDō共同作業の招待\n\n%@\n\n招待相手: %@", "Jemputan kolaborasi toDō untuk %@\n\n%@\n\nJemputan kepada: %@", "คำเชิญให้ทำงานร่วมกันใน toDō สำหรับ %@\n\n%@\n\nผู้ได้รับเชิญ: %@", "%@ کے لیے toDō تعاون کی دعوت\n\n%@\n\nمدعو: %@", "发给 %@ 的 toDō 协作邀请\n\n%@\n\n受邀者：%@"],
  ["دعوة تعاون toDō لـ %@\n\n%@\n\nالمدعو: %@", "Invitación de colaboración de toDō para %@\n\n%@\n\nInvitado: %@", "%@ के लिए toDō सहयोग निमंत्रण\n\n%@\n\nआमंत्रित: %@", "Invito alla collaborazione toDō per %@\n\n%@\n\nInvitato: %@", "%@へのtoDō共同作業の招待\n\n%@\n\n招待相手: %@", "Jemputan kolaborasi toDō untuk %@\n\n%@\n\nJemputan kepada: %@", "คำเชิญให้ทำงานร่วมกันใน toDō สำหรับ %@\n\n%@\n\nผู้ได้รับเชิญ: %@", "%@ کے لیے toDō تعاون کی دعوت\n\n%@\n\nمدعو: %@", "发给 %@ 的 toDō 协作邀请\n\n%@\n\n受邀者：%@"],
  ["دعوة تعاون toDō", "Invitación de colaboración de toDō", "toDō सहयोग निमंत्रण", "Invito alla collaborazione toDō", "toDō共同作業の招待", "Jemputan kolaborasi toDō", "คำเชิญทำงานร่วมกันใน toDō", "toDō تعاون کی دعوت", "toDō 协作邀请"],
  ["دعوة تعاون toDō!", "¡Invitación de colaboración de toDō!", "toDō सहयोग निमंत्रण!", "Invito alla collaborazione toDō!", "toDō共同作業の招待！", "Jemputan kolaborasi toDō!", "คำเชิญทำงานร่วมกันใน toDō!", "toDō تعاون کی دعوت!", "toDō 协作邀请！"],
  ["toDō هو نظام إنتاجية مصمم للمستخدم ليساعدك على البقاء منظمًا دون أن يقف في طريقك. من المهام اليومية وقوائم التسوق إلى الخطط الأكبر وكل ما يتجاوزها، صُمم ليعمل بالطريقة التي تعمل بها.", "toDō es un sistema de productividad creado para ayudarte a mantenerte organizado sin interponerse en tu camino. Desde las tareas diarias y las listas de compras hasta los planes más grandes y todo lo demás, está diseñado para funcionar como tú.", "toDō उपयोगकर्ता के लिए बनाया गया उत्पादकता सिस्टम है, जो रास्ते में आए बिना आपको व्यवस्थित रहने में मदद करता है। रोज़मर्रा के कार्यों और खरीदारी सूचियों से लेकर बड़ी योजनाओं और उससे आगे तक, इसे आपके काम करने के तरीके के अनुसार बनाया गया है।", "toDō è un sistema di produttività pensato per aiutarti a restare organizzato senza intralciarti. Dalle attività quotidiane e le liste della spesa ai piani più grandi e oltre, è progettato per funzionare come fai tu.", "toDōは、邪魔をせずに整理整頓を支えるユーザー向けの生産性システムです。日々のタスクや買い物リストから大きな計画まで、あなたの使い方に合わせて機能します。", "toDō ialah sistem produktiviti yang dibina untuk membantu anda kekal teratur tanpa mengganggu. Daripada tugas harian dan senarai beli-belah hingga rancangan besar dan segala yang melangkauinya, ia direka untuk berfungsi mengikut cara anda.", "toDō คือระบบเพิ่มประสิทธิภาพที่สร้างมาเพื่อช่วยให้คุณจัดระเบียบได้โดยไม่ขวางทาง ตั้งแต่งานประจำวันและรายการช้อปปิ้ง ไปจนถึงแผนใหญ่และทุกสิ่งที่มากกว่านั้น ออกแบบมาให้ทำงานในแบบของคุณ", "toDō صارف کے لیے بنایا گیا پیداواری نظام ہے جو آپ کے راستے میں آئے بغیر منظم رہنے میں مدد دیتا ہے۔ روزمرہ کے کاموں اور خریداری کی فہرستوں سے لے کر بڑے منصوبوں اور اس سے آگے تک، اسے آپ کے کام کرنے کے انداز کے مطابق بنایا گیا ہے۔", "toDō 是一套以用户为中心的效率系统，帮助你保持井然有序而不打扰你的节奏。从日常任务和购物清单，到更大的计划以及更多内容，它都旨在按照你的方式工作。"],
  ["فعّل Apple Intelligence في toDō قبل استخدام هذا الإجراء.", "Activa Apple Intelligence en toDō antes de usar esta acción.", "इस कार्रवाई का उपयोग करने से पहले toDō में Apple Intelligence चालू करें।", "Attiva Apple Intelligence in toDō prima di usare questa azione.", "このアクションを使う前に、toDōでApple Intelligenceをオンにしてください。", "Hidupkan Apple Intelligence dalam toDō sebelum menggunakan tindakan ini.", "เปิด Apple Intelligence ใน toDō ก่อนใช้การดำเนินการนี้", "یہ کارروائی استعمال کرنے سے پہلے toDō میں Apple Intelligence آن کریں۔", "使用此操作前，请在 toDō 中开启 Apple Intelligence。"],
  ["استخدم من 3 إلى 30 حرفًا أو رقمًا أو نقطة أو شرطة سفلية. اسم المستخدم هو الطريقة التي يتعرّف بها المتعاونون عليك.", "Usa entre 3 y 30 letras, números, puntos o guiones bajos. Tu nombre de usuario es la forma en que te reconocen los colaboradores.", "3–30 अक्षर, अंक, बिंदु या अंडरस्कोर का उपयोग करें। आपका उपयोगकर्ता नाम सहयोगियों को आपकी पहचान बताता है।", "Usa da 3 a 30 lettere, numeri, punti o trattini bassi. Il nome utente è il modo in cui i collaboratori ti riconoscono.", "3〜30文字の英字、数字、ピリオド、アンダースコアを使用してください。ユーザー名は共同作業者があなたを認識する名前です。", "Gunakan 3–30 huruf, nombor, titik atau garis bawah. Nama pengguna ialah cara kolaborator mengenali anda.", "ใช้ตัวอักษร ตัวเลข จุด หรือขีดล่าง 3–30 ตัว ชื่อผู้ใช้คือชื่อที่ผู้ร่วมงานใช้ระบุคุณ", "3 سے 30 حروف، اعداد، نقطوں یا انڈر اسکور استعمال کریں۔ آپ کا صارف نام ساتھیوں کو آپ کی شناخت بتاتا ہے۔", "请使用 3–30 个字母、数字、句点或下划线。用户名是协作者识别你的方式。"],
  ["استخدم رابط صورة آمنًا عبر https.", "Usa un enlace de imagen seguro mediante https.", "एक सुरक्षित https चित्र लिंक का उपयोग करें।", "Usa un link immagine sicuro https.", "安全なhttps画像リンクを使用してください。", "Gunakan pautan imej https yang selamat.", "ใช้ลิงก์รูป https ที่ปลอดภัย", "محفوظ https تصویر کا لنک استعمال کریں۔", "使用安全的 https 图片链接。"],
  ["استخدم رابط صورة آمنًا. ينزّل toDō نسخة محلية قبل سؤالك عن مكان استخدامها.", "Usa un enlace de imagen seguro. toDō descarga una copia local antes de preguntarte dónde usarla.", "सुरक्षित चित्र लिंक का उपयोग करें। toDō यह पूछने से पहले स्थानीय प्रति डाउनलोड करता है कि इसका उपयोग कहाँ करना है।", "Usa un link immagine sicuro. toDō scarica una copia locale prima di chiederti dove usarla.", "安全な画像リンクを使用してください。toDōは利用場所を尋ねる前にローカルコピーをダウンロードします。", "Gunakan pautan imej selamat. toDō memuat turun salinan setempat sebelum bertanya tempat menggunakannya.", "ใช้ลิงก์รูปที่ปลอดภัย toDō จะดาวน์โหลดสำเนาในเครื่องก่อนถามว่าจะใช้ที่ใด", "محفوظ تصویر کا لنک استعمال کریں۔ toDō یہ پوچھنے سے پہلے مقامی کاپی ڈاؤن لوڈ کرتی ہے کہ اسے کہاں استعمال کرنا ہے۔", "使用安全的图片链接。toDō 会先下载本地副本，再询问使用位置。"],
  ["استخدم اسم مستخدم مكونًا من أحرف وأرقام ونقاط وشرطات سفلية.", "Usa un nombre de usuario con letras, números, puntos y guiones bajos.", "अक्षरों, अंकों, बिंदुओं और अंडरस्कोर वाला उपयोगकर्ता नाम चुनें।", "Usa un nome utente con lettere, numeri, punti e trattini bassi.", "英字、数字、ピリオド、アンダースコアを含むユーザー名を使用してください。", "Gunakan nama pengguna yang mengandungi huruf, nombor, titik dan garis bawah.", "ใช้ชื่อผู้ใช้ที่มีตัวอักษร ตัวเลข จุด และขีดล่าง", "حروف، اعداد، نقاط اور انڈر اسکور والا صارف نام استعمال کریں۔", "使用包含字母、数字、句点和下划线的用户名。"],
  ["استخدام رابط صورة", "Usar un enlace de imagen", "चित्र लिंक का उपयोग करें", "Usa link immagine", "画像リンクを使用", "Gunakan Pautan Imej", "ใช้ลิงก์รูป", "تصویر کا لنک استعمال کریں", "使用图片链接"],
  ["استخدم صورة أصغر من 5 ميغابايت.", "Usa una imagen de menos de 5 MB.", "5 MB से छोटी छवि का उपयोग करें।", "Usa un'immagine più piccola di 5 MB.", "5 MB未満の画像を使用してください。", "Gunakan imej yang lebih kecil daripada 5 MB.", "ใช้รูปที่มีขนาดเล็กกว่า 5 MB", "5 MB سے چھوٹی تصویر استعمال کریں۔", "使用小于 5 MB 的图片。"],
  ["استخدام الصورة", "Usar imagen", "चित्र का उपयोग करें", "Usa immagine", "画像を使用", "Gunakan Imej", "ใช้รูป", "تصویر استعمال کریں", "使用图片"],
  ["استخدام رابط الصورة", "Usar enlace de imagen", "चित्र लिंक का उपयोग करें", "Usa link immagine", "画像リンクを使用", "Gunakan Pautan Imej", "ใช้ลิงก์รูป", "تصویر کا لنک استعمال کریں", "使用图片链接"],
  ["استخدام هذا الرابط", "Usar este enlace", "इस लिंक का उपयोग करें", "Usa questo link", "このリンクを使用", "Gunakan Pautan Ini", "ใช้ลิงก์นี้", "یہ لنک استعمال کریں", "使用此链接"],
  ["اسم المستخدم", "Nombre de usuario", "उपयोगकर्ता नाम", "Nome utente", "ユーザー名", "Nama pengguna", "ชื่อผู้ใช้", "صارف نام", "用户名"],
  ["ما الذي تريد إنجازه؟", "¿Qué quieres conseguir?", "आप क्या करना चाहते हैं?", "Cosa vuoi realizzare?", "何を達成したいですか？", "Apakah yang ingin anda selesaikan?", "คุณต้องการทำอะไรให้เสร็จ", "آپ کیا مکمل کرنا چاہتے ہیں؟", "你想完成什么？"],
  ["أين ينبغي استخدام هذه الصورة؟", "¿Dónde debe usarse esta imagen?", "इस चित्र का उपयोग कहाँ किया जाना चाहिए?", "Dove deve essere usata questa immagine?", "この画像をどこで使用しますか？", "Di manakah imej ini patut digunakan?", "ควรใช้รูปนี้ที่ใด", "یہ تصویر کہاں استعمال کی جائے؟", "这张图片应在哪里使用？"],
  ["يمكنك مراجعة هذه الدعوة أو رفضها قبل الانضمام إلى القائمة المشتركة.", "Puedes revisar o rechazar esta invitación antes de unirte a la lista compartida.", "साझा सूची में शामिल होने से पहले आप इस निमंत्रण की समीक्षा या अस्वीकृति कर सकते हैं।", "Puoi esaminare o rifiutare questo invito prima di unirti alla lista condivisa.", "共有リストに参加する前に、この招待を確認または辞退できます。", "Anda boleh menyemak atau menolak jemputan ini sebelum menyertai senarai dikongsi.", "คุณตรวจสอบหรือปฏิเสธคำเชิญนี้ได้ก่อนเข้าร่วมรายการที่แชร์", "مشترکہ فہرست میں شامل ہونے سے پہلے آپ اس دعوت کا جائزہ لے یا اسے مسترد کر سکتے ہیں۔", "加入共享列表前，你可以查看或拒绝此邀请。"],
  ["لقد تلقيت دعوة للتعاون مع هذا المستخدم.", "Has recibido una invitación para colaborar con este usuario.", "आपको इस उपयोगकर्ता के साथ सहयोग करने के लिए आमंत्रित किया गया है।", "Hai ricevuto un invito a collaborare con questo utente.", "このユーザーから共同作業への招待が届いています。", "Anda telah dijemput untuk bekerjasama dengan pengguna ini.", "คุณได้รับคำเชิญให้ทำงานร่วมกับผู้ใช้นี้", "آپ کو اس صارف کے ساتھ تعاون کرنے کی دعوت دی گئی ہے۔", "你已收到与此用户协作的邀请。"],
  ["تعذر حفظ صورة ملفك الشخصي. حاول مرة أخرى.", "No se pudo guardar tu imagen de perfil. Inténtalo de nuevo.", "आपका प्रोफ़ाइल चित्र सहेजा नहीं जा सका। फिर कोशिश करें।", "Non è stato possibile salvare la tua immagine del profilo. Riprova.", "プロフィール画像を保存できませんでした。もう一度お試しください。", "Gambar profil anda tidak dapat disimpan. Cuba lagi.", "บันทึกรูปโปรไฟล์ของคุณไม่ได้ ลองอีกครั้ง", "آپ کی پروفائل تصویر محفوظ نہیں ہو سکی۔ دوبارہ کوشش کریں۔", "无法保存你的头像。请重试。"]
].freeze

data = JSON.parse(File.read(CATALOG_PATH))
strings = data.fetch("strings")
missing_keys = strings.each_with_object([]) do |(key, entry), keys|
  next unless key.match?(/[A-Za-z]/)

  missing = LANGUAGES.any? do |language|
    value = entry.dig("localizations", language, "stringUnit", "value")
    value.nil? || value.strip.empty?
  end
  keys << key if missing
end

if missing_keys.empty?
  puts "No missing catalog translations."
  exit 0
end

raise "Translation table has #{TRANSLATIONS.length} rows; catalog has #{missing_keys.length} missing keys" unless TRANSLATIONS.length == missing_keys.length

missing_keys.each_with_index do |key, index|
  entry = strings.fetch(key)
  LANGUAGES.each_with_index do |language, language_index|
    next if entry.dig("localizations", language, "stringUnit", "value").to_s.strip != ""

    value = TRANSLATIONS.fetch(index).fetch(language_index)
    raise "Empty translation for #{key.inspect} (#{language})" if value.strip.empty?

    entry["localizations"] ||= {}
    entry["localizations"][language] = {
      "stringUnit" => {
        "state" => "translated",
        "value" => value
      }
    }
  end
end

File.write(CATALOG_PATH, JSON.pretty_generate(data) + "\n")
puts "Filled #{missing_keys.length} catalog keys across #{LANGUAGES.length} languages."
